### PR TITLE
add send_continue method.

### PR DESCRIPTION
**Pull request by sassembla**

### CODE REVIEW

**Comment by agentzh** [comment]
@sassembla Thanks for the patch! Mind to add some corresponding test cases to the existing test suite for this new feature? Thanks!

**Comment by bungle** [comment]
And documentation would be nice as well (add that function to README.markdown).

**Comment by sassembla** [comment]
@agentzh @bungle Oh~ I missed that. I'll add tests & doc later.

**Comment by agentzh** [comment]
@sassembla Thanks!

**Pull request merged**
